import { Inter } from 'next/font/google'
import './globals.css'
import { StateContextProvider } from '@/context.js'
import WalletConnectionProvider from '@/context.js/WalletConnectionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <WalletConnectionProvider>
      <StateContextProvider>
        <body className={inter.className}>{children}</body>
      </StateContextProvider>
    </WalletConnectionProvider>
    </html>
  )
}
